# fly.toml file generated for kronos on 2023-03-04T23:36:09+08:00

app = # Your FLY_APP name eg. "martiansunset"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
SWAP = "true"
PLANET= # Your planet name in "" eg. "sampel-palnet"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "100s"
    interval = "120s"
    restart_limit = 0
    timeout = "2s"
